/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmobil2019;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class formpenyewa extends javax.swing.JFrame {
    private Connection conectionpenyewa;
    private ResultSet resultsetpenyewa;
    private Statement statementpenyewa;
    String db_sql = "";
    
    private String idpenyewa,namapenyewa,alamatpenyewa,statuspenyewa,nohp,noktp;

    
    public formpenyewa() {
        initComponents();
        Koneksipenyewa();
        Tampildatapenyewa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtidpenyewa = new javax.swing.JTextField();
        txtnamapenyewa = new javax.swing.JTextField();
        txtalamatpenyewa = new javax.swing.JTextField();
        txtnohppenyewa = new javax.swing.JTextField();
        txtnoktppenyewa = new javax.swing.JTextField();
        cmbstatuspenyewa = new javax.swing.JComboBox<>();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpenyewa = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setText("ID Penyewa");

        jLabel2.setText("Nama Penyewa");

        jLabel3.setText("Alamat");

        jLabel4.setText("No HP");

        jLabel5.setText("NO KTP");

        jLabel6.setText("Status");

        txtidpenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpenyewaActionPerformed(evt);
            }
        });
        txtidpenyewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidpenyewaKeyPressed(evt);
            }
        });

        txtnamapenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapenyewaActionPerformed(evt);
            }
        });
        txtnamapenyewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamapenyewaKeyPressed(evt);
            }
        });

        txtnohppenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnohppenyewaActionPerformed(evt);
            }
        });

        cmbstatuspenyewa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "READY", "NOT READY" }));
        cmbstatuspenyewa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbstatuspenyewaItemStateChanged(evt);
            }
        });
        cmbstatuspenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbstatuspenyewaActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        tblpenyewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Penyewa", "Nama Penyewa", "Alamat", "No HP", "No KTP", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblpenyewa);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/employee.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbstatuspenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtidpenyewa, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(txtnamapenyewa)
                                    .addComponent(txtalamatpenyewa)
                                    .addComponent(txtnohppenyewa)
                                    .addComponent(txtnoktppenyewa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnsimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidpenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnamapenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtalamatpenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnohppenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtnoktppenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbstatuspenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnbatal)
                    .addComponent(btnedit)
                    .addComponent(btnhapus)
                    .addComponent(btnkeluar))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Master");

        jMenuItem1.setText("Formmobil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Formpenyewa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        jMenuItem3.setText("FormRental");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("FormPengembalian");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidpenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpenyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpenyewaActionPerformed

    private void txtnamapenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapenyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamapenyewaActionPerformed

    private void txtnohppenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnohppenyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnohppenyewaActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        frmlogin login=new frmlogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        idpenyewa = String.valueOf(txtidpenyewa.getText());
        namapenyewa = String.valueOf(txtnamapenyewa.getText());
        alamatpenyewa = String.valueOf(txtalamatpenyewa.getText());
        statuspenyewa = String.valueOf(cmbstatuspenyewa.getSelectedItem());
        nohp = String.valueOf(txtnohppenyewa.getText());
        noktp = String.valueOf(txtnoktppenyewa.getText());
        
        if(idpenyewa.isEmpty())
            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Form!");
        else if(namapenyewa.isEmpty())
            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Form!");
        else if(alamatpenyewa.isEmpty())
            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Form!");
        else if(statuspenyewa.equals("PILIH"))
            JOptionPane.showMessageDialog(null, "Status Belum Dipilih!");
        else if(nohp.isEmpty())
            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Form!");
        else if (noktp.isEmpty())
            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Form!");
        else
            try{
                db_sql = "insert into tabel_penyewa(idpenyewa,namapenyewa,alamatpenyewa,"
                        + "noktppenyewa,nohppenyewa,status)VALUE"
                        + "('"+idpenyewa+"','"+namapenyewa+"','"+alamatpenyewa+"','"+noktp+"','"+nohp+"','"+statuspenyewa+"')";
                statementpenyewa=conectionpenyewa.createStatement();
                statementpenyewa.execute(db_sql);
                Tampildatapenyewa();
                Clear();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan\n"+e.getMessage());
            }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtidpenyewaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpenyewaKeyPressed
        // TODO add your handling code here:
        idpenyewa = txtidpenyewa.getText();
        int tekanenter = evt.getKeyCode();
        if(tekanenter==10){
            try{
                db_sql = "select * from tabel_penyewa where idpenyewa= '"+idpenyewa+"'";
                statementpenyewa=conectionpenyewa.createStatement();
                resultsetpenyewa=statementpenyewa.executeQuery(db_sql);
                while (resultsetpenyewa.next()){
                txtnamapenyewa.setText(resultsetpenyewa.getString("namapenyewa"));
                txtalamatpenyewa.setText(resultsetpenyewa.getString(3));
                txtnoktppenyewa.setText(resultsetpenyewa.getString(4));
                txtnohppenyewa.setText(resultsetpenyewa.getString(5));
                cmbstatuspenyewa.setSelectedItem(resultsetpenyewa.getString(6));
                JOptionPane.showMessageDialog(null, "Data Ditemukan!");
                }
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan!\n"+e.getMessage());
            }
        }
    }//GEN-LAST:event_txtidpenyewaKeyPressed

    private void txtnamapenyewaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamapenyewaKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtnamapenyewaKeyPressed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnbatalActionPerformed

    
    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        idpenyewa = String.valueOf(txtidpenyewa.getText());
        namapenyewa =String.valueOf(txtnamapenyewa.getText());
        alamatpenyewa =String.valueOf(txtalamatpenyewa.getText());
        nohp=String.valueOf(txtnohppenyewa.getText());
        noktp=String.valueOf(txtnoktppenyewa.getText());
        statuspenyewa=String.valueOf(cmbstatuspenyewa.getSelectedItem());
        
        try{
            db_sql = "update tabel_penyewaset namapenyewa='"+namapenyewa+"',alamatpenyewa='"+alamatpenyewa+"',nohppenyewa='"+nohp+"',noktppenyewa='"+noktp+"',status='"+statuspenyewa+"'where idpenyewa='"+idpenyewa+"'";
            statementpenyewa=conectionpenyewa.createStatement();
            statementpenyewa.execute(db_sql);
            Clear();
            Tampildatapenyewa();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dirubah!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Dirubah\n"+e.getMessage());
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed

        idpenyewa = String.valueOf(txtidpenyewa.getText());
        
        try{
            db_sql="delete from tabel_penyewa where idpenyewa='"+idpenyewa+"'";
            statementpenyewa=conectionpenyewa.createStatement();
            statementpenyewa.execute(db_sql);
            JOptionPane.showMessageDialog(null, "Data Penyewa Berhasil Dihapus!");
            Clear();
            Tampildatapenyewa();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus!\n"+e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        formrental rental = new formrental();
        rental.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        formmobil mobil = new formmobil();
        mobil.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        formpenyewa penyewa = new formpenyewa();
        penyewa.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        frmpengembalian kembali=new frmpengembalian();
        kembali.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void cmbstatuspenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbstatuspenyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbstatuspenyewaActionPerformed

    private void cmbstatuspenyewaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbstatuspenyewaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbstatuspenyewaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formpenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formpenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formpenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formpenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formpenyewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cmbstatuspenyewa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblpenyewa;
    private javax.swing.JTextField txtalamatpenyewa;
    private javax.swing.JTextField txtidpenyewa;
    private javax.swing.JTextField txtnamapenyewa;
    private javax.swing.JTextField txtnohppenyewa;
    private javax.swing.JTextField txtnoktppenyewa;
    // End of variables declaration//GEN-END:variables

    private void Koneksipenyewa() {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conectionpenyewa=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_rentalmobilsecond","root","");
            System.out.println("Koneksi Berhasil");
        } catch (Exception e) {
            System.out.println("Koneksi Gagal");
          
      }
    }

    private void Tampildatapenyewa() {
        DefaultTableModel defaulttablemodel = new DefaultTableModel();
        
        defaulttablemodel.addColumn("NO");
        defaulttablemodel.addColumn("ID Penyewa");
        defaulttablemodel.addColumn("Nama Penyewa");
        defaulttablemodel.addColumn("Alamat");
        defaulttablemodel.addColumn("No KTP");
        defaulttablemodel.addColumn("No HP");
        defaulttablemodel.addColumn("Status");
        
        try{
            int i = 1;
            statementpenyewa=conectionpenyewa.createStatement();
            resultsetpenyewa=statementpenyewa.executeQuery("select * from tabel_penyewa");
            while (resultsetpenyewa.next())
                defaulttablemodel.addRow(new Object[]{
                    (""+i++),
                    resultsetpenyewa.getString(1),   resultsetpenyewa.getString(2),
                    resultsetpenyewa.getString(3),   resultsetpenyewa.getString(4),
                    resultsetpenyewa.getString(5),   resultsetpenyewa.getString(6)
                });
            tblpenyewa.setModel(defaulttablemodel);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Ditampilkan!\n"+e.getMessage());
        }
    }

    private void Clear() {
        txtidpenyewa.setText("");
        txtnamapenyewa.setText("");
        txtalamatpenyewa.setText("");
        txtnohppenyewa.setText("");
        txtnoktppenyewa.setText("");
        cmbstatuspenyewa.setSelectedItem("PILIH");
    }
}
