/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmobil2019;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.util.calendar.BaseCalendar;

public class formrental extends javax.swing.JFrame {
    private Connection connectionrental;
    private Statement statemenrental;
    private ResultSet resultsetrental;
    private ResultSet resultsetmobil;
    private ResultSet resultsetpenyewa;
    private String sqlrental="";
    
    private String idrental,pilihansewa,idpenyewa,idmobil,namapenyewa,namamobil,bmmobil,status,tanggal, hargarental;
    
    public formrental() {
        initComponents();
        KoneksiRental();
        Clear();
        TampilData(sqlrental);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtidrentalfrmrental = new javax.swing.JTextField();
        cmbpilihansewafrmrental = new javax.swing.JComboBox<>();
        cmbidpenyewafrmrental = new javax.swing.JComboBox<>();
        cmbidmobilfrmrental = new javax.swing.JComboBox<>();
        txtnamapenyewafrmrental = new javax.swing.JTextField();
        txtnamamobilfrmrental = new javax.swing.JTextField();
        txtbmmobilfrmrental = new javax.swing.JTextField();
        txthargarentalfrmrental = new javax.swing.JTextField();
        txtstatusfrmrental = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblrental = new javax.swing.JTable();
        tanggalrental = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setText("ID Rental");

        jLabel2.setText("Pilihan Sewa");

        jLabel3.setText("ID Penyewa");

        jLabel4.setText("ID Mobil");

        jLabel5.setText("Nama Penyewa");

        jLabel6.setText("Nama Mobil");

        jLabel7.setText("BM Mobil");

        jLabel8.setText("Harga Rental");

        jLabel9.setText("Tanggal");

        jLabel10.setText("Status");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/car.png"))); // NOI18N

        txtidrentalfrmrental.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidrentalfrmrentalKeyPressed(evt);
            }
        });

        cmbpilihansewafrmrental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "SEWA" }));
        cmbpilihansewafrmrental.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbpilihansewafrmrentalItemStateChanged(evt);
            }
        });
        cmbpilihansewafrmrental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpilihansewafrmrentalActionPerformed(evt);
            }
        });

        cmbidpenyewafrmrental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbidpenyewafrmrental.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbidpenyewafrmrentalItemStateChanged(evt);
            }
        });
        cmbidpenyewafrmrental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbidpenyewafrmrentalActionPerformed(evt);
            }
        });

        cmbidmobilfrmrental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbidmobilfrmrental.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbidmobilfrmrentalItemStateChanged(evt);
            }
        });
        cmbidmobilfrmrental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbidmobilfrmrentalActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        tblrental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Rental", "ID Mobil", "ID Penyewa", "Harga Rental", "Tanggal Rental"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblrental);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnsimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtstatusfrmrental, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbpilihansewafrmrental, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbidpenyewafrmrental, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbidmobilfrmrental, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnamapenyewafrmrental, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txthargarentalfrmrental, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbmmobilfrmrental, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnamamobilfrmrental)
                                    .addComponent(tanggalrental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtidrentalfrmrental))))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidrentalfrmrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbpilihansewafrmrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbidpenyewafrmrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cmbidmobilfrmrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtnamapenyewafrmrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtnamamobilfrmrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtbmmobilfrmrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txthargarentalfrmrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan)
                            .addComponent(btnbatal)
                            .addComponent(btnedit)
                            .addComponent(btnhapus)
                            .addComponent(btnkeluar)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tanggalrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtstatusfrmrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jMenu1.setText("Master");

        jMenuItem1.setText("FormMobil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("FormPenyewa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        jMenuItem3.setText("FormRental");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("FormPengembalian");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        frmlogin login = new frmlogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void txtidrentalfrmrentalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidrentalfrmrentalKeyPressed
        idrental=String.valueOf(txtidrentalfrmrental.getText());
        int tekanenter = evt.getKeyCode();
        if(tekanenter==10){
            try{
                sqlrental="select * from tabel_rental where idrental='"+idrental+"'";
                statemenrental = connectionrental.createStatement();
                resultsetrental = statemenrental.executeQuery(sqlrental);
                while (resultsetrental.next()){
                   cmbidmobilfrmrental.setSelectedItem(resultsetrental.getString("idmobil"));
                   cmbidpenyewafrmrental.setSelectedItem(resultsetrental.getString("idpenyewa"));
                   txtnamapenyewafrmrental.setText(resultsetrental.getString("namapenyewa"));
                   txtnamamobilfrmrental.setText(resultsetrental.getString("namamobil"));
                   txthargarentalfrmrental.setText(resultsetrental.getString("hargarental"));
//                   tanggalrental.setDate(resultsetrental.getDate("tanggalrental"));
                   txtstatusfrmrental.setText(resultsetrental.getString("status"));
                   
                   JOptionPane.showMessageDialog(null, "Data Ditemukan");
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data Gagal Ditemukan\n"+e.getMessage());
                cmbidmobilfrmrental.requestFocus();
                
            }
            try{
                cmbidmobilfrmrental.removeAllItems();
                sqlrental="select * from tabel_rental where idrental='"+idrental+"'";
                statemenrental=connectionrental.createStatement();
                resultsetmobil = statemenrental.executeQuery(sqlrental);
                while(resultsetmobil.next()){
                    String AliasID = resultsetmobil.getString("idmobil");
                    cmbidmobilfrmrental.addItem(AliasID);
                    cmbpilihansewafrmrental.setEnabled(false);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Gagal Menampilkan ID Mobil\n"+e.getMessage());
            }
            
            try{
                cmbidpenyewafrmrental.removeAllItems();
                sqlrental="select * from tabel_rental where idrental='"+idrental+"'";
                statemenrental=connectionrental.createStatement();
                resultsetpenyewa=statemenrental.executeQuery(sqlrental);
                while(resultsetpenyewa.next()){
                    String AliasIDpenyewa= resultsetpenyewa.getString("idpenyewa");
                    cmbidpenyewafrmrental.addItem(AliasIDpenyewa);
                    cmbpilihansewafrmrental.setEnabled(false);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Gagal Menampilkan ID Penyewa\n"+e.getMessage());
            }
        }
    }//GEN-LAST:event_txtidrentalfrmrentalKeyPressed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        idrental = String.valueOf(txtidrentalfrmrental.getText());
        pilihansewa=String.valueOf(cmbpilihansewafrmrental.getSelectedIndex()).toString();
        idpenyewa=cmbidpenyewafrmrental.getItemAt(cmbpilihansewafrmrental.getSelectedIndex()).toString();
        idmobil=cmbidmobilfrmrental.getItemAt(cmbidmobilfrmrental.getSelectedIndex()).toString();
        namapenyewa=String.valueOf(txtnamapenyewafrmrental.getText());
        //tanggal = String.valueOf(tanggalrental.getDate());
        namamobil=String.valueOf(txtnamamobilfrmrental.getText());
        bmmobil=String.valueOf(txtbmmobilfrmrental.getText());
        hargarental=String.valueOf(txthargarentalfrmrental.getText());
        status=cmbpilihansewafrmrental.getItemAt(cmbpilihansewafrmrental.getSelectedIndex()).toString();
        SimpleDateFormat simple=new SimpleDateFormat("yyyy-MM-dd");
        tanggal=simple.format(tanggalrental.getDate());
        if(idrental.isEmpty())
            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Form");
        else if(pilihansewa.equals("PILIH"))
            JOptionPane.showMessageDialog(null, "Pilihan Sewa Belum Dipilih");
        else if(idpenyewa.equals("PILIH"))
            JOptionPane.showMessageDialog(null, "id penyewa Belum Dipilih");
        else if(idmobil.equals("PILIH"))
            JOptionPane.showMessageDialog(null, "Id Mobil Belum Dipilih");
        else{
            try{
                sqlrental="insert into tabel_rental(idrental, idpenyewa, idmobil, namapenyewa, namamobil, hargarental, tanggalrental, status)VALUE"
                        + "('"+idrental+"','"+idpenyewa+"','"+idmobil+"','"+namapenyewa+"','"+namamobil+"','"+hargarental+"','"+tanggal+"','"+status+"')";
                statemenrental=connectionrental.createStatement();
                statemenrental.execute(sqlrental);
                TampilData(sqlrental);
                Clear();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan\n"+e.getMessage());
            }
        }
        try{
            status="Not Ready";
            sqlrental="update tabel_mobil set status='"+status+"' where idmobil='"+idmobil+"'";
            statemenrental=connectionrental.createStatement();
            statemenrental.execute(sqlrental);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Program Error\n"+e.getMessage());
        }
        
        try{
            status="Not Ready";
            sqlrental="update tabel_penyewa set status='"+status+"' where idpenyewa='"+idpenyewa+"'";
            statemenrental=connectionrental.createStatement();
            statemenrental.execute(sqlrental);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Programs Error\n"+e.getMessage());
        }
            
        
        
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void cmbpilihansewafrmrentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpilihansewafrmrentalActionPerformed
        // TODO add your handling code here:\
        if(cmbpilihansewafrmrental.getSelectedItem()=="SEWA");{
        status=String.valueOf(cmbpilihansewafrmrental.getSelectedItem());
        pilihansewa=String.valueOf(txtstatusfrmrental.getText());
        pilihansewa="READY";
        txtstatusfrmrental.setText(String.valueOf(pilihansewa));
    }
        txtstatusfrmrental.setText(String.valueOf(pilihansewa));
        
        if(cmbpilihansewafrmrental.getSelectedItem()=="SEWA"){
            cmbidmobilfrmrental.removeAllItems();
            cmbidmobilfrmrental.addItem("PILIH");
            try{
                status=String.valueOf(cmbpilihansewafrmrental.getSelectedItem());
                status="READY";
                sqlrental="select * from tabel_mobil where status = '"+status+"'";
                statemenrental=connectionrental.createStatement();
                resultsetmobil=statemenrental.executeQuery(sqlrental);
                while(resultsetmobil.next()){
                     String Aliaskd= resultsetmobil.getString("idmobil");
                     cmbidmobilfrmrental.addItem(Aliaskd);
                     
                }
                   
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Gagal Menampilkan ID Mobil\n"+e.getMessage());
            }
            cmbidpenyewafrmrental.removeAllItems();
            cmbidpenyewafrmrental.addItem("PILIH");
            try{
                status=String.valueOf(cmbpilihansewafrmrental.getSelectedItem());
                status="READY";
                sqlrental="select * from tabel_penyewa where status='"+status+"'";
                statemenrental=connectionrental.createStatement();
                resultsetpenyewa=statemenrental.executeQuery(sqlrental);
                while(resultsetpenyewa.next()){
                    String Aliaskdmobil=resultsetpenyewa.getString("idpenyewa");
                    cmbidpenyewafrmrental.addItem(Aliaskdmobil);

                
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan ID Penyewa\n"+e.getMessage());
        }
    
        
        }
        
    }//GEN-LAST:event_cmbpilihansewafrmrentalActionPerformed

    private void cmbidpenyewafrmrentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbidpenyewafrmrentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbidpenyewafrmrentalActionPerformed

    private void cmbidpenyewafrmrentalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbidpenyewafrmrentalItemStateChanged
        // TODO add your handling code here:
        try{
            sqlrental="select * from tabel_penyewa where idpenyewa='"+cmbidpenyewafrmrental.getSelectedItem()+"'";
            statemenrental=connectionrental.createStatement();
            resultsetpenyewa=statemenrental.executeQuery(sqlrental);
            while(resultsetpenyewa.next()){
                txtnamapenyewafrmrental.setText(resultsetpenyewa.getString("namapenyewa"));
            }
            txtnamapenyewafrmrental.requestFocus();
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_cmbidpenyewafrmrentalItemStateChanged

    private void cmbidmobilfrmrentalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbidmobilfrmrentalItemStateChanged
        // TODO add your handling code here:
        try{
            sqlrental="select * from tabel_mobil where idmobil='"+cmbidmobilfrmrental.getSelectedItem()+"'";
            statemenrental=connectionrental.createStatement();
            resultsetmobil=statemenrental.executeQuery(sqlrental);
            while(resultsetmobil.next()){
                txtnamamobilfrmrental.setText(resultsetmobil.getString("namamobil"));
                txtbmmobilfrmrental.setText(resultsetmobil.getString("bmmobil"));
                txthargarentalfrmrental.setText(resultsetmobil.getString("hargamobil"));
            }
            txtnamamobilfrmrental.requestFocus();
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_cmbidmobilfrmrentalItemStateChanged

    private void tanggalrentalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalrentalPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tanggalrentalPropertyChange

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        formmobil mobil= new formmobil();
        mobil.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        formpenyewa penyewa = new formpenyewa();
        penyewa.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        idrental=String.valueOf(txtidrentalfrmrental.getText());
        
        try{
            sqlrental="delete from tabel_rental where idrental='"+idrental+"'";
            statemenrental=connectionrental.createStatement();
            statemenrental.execute(sqlrental);
            Clear();
            TampilData(sqlrental);
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus!\n"+e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        idrental=String.valueOf(txtidrentalfrmrental.getText());
        idmobil=String.valueOf(cmbidmobilfrmrental.getSelectedItem());
        idpenyewa=String.valueOf(cmbidpenyewafrmrental.getSelectedItem());
        hargarental=String.valueOf(txthargarentalfrmrental.getText());
        
        
        try{
            sqlrental="update tabel_rental set idmobil='"+idmobil+"',idpenyewa='"+idpenyewa+"',hargarental='"+hargarental+"',tanggalrental='"+tanggal+"' where idmobil='"+idmobil+"'";
            statemenrental=connectionrental.createStatement();
            statemenrental.execute(sqlrental);
            Clear();
            TampilData(sqlrental);
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Data Gagal Diubah\n"+e.getMessage());
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        frmpengembalian kembali=new frmpengembalian();
        kembali.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void cmbidmobilfrmrentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbidmobilfrmrentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbidmobilfrmrentalActionPerformed

    private void cmbpilihansewafrmrentalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbpilihansewafrmrentalItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbpilihansewafrmrentalItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formrental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formrental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formrental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formrental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formrental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cmbidmobilfrmrental;
    private javax.swing.JComboBox<String> cmbidpenyewafrmrental;
    private javax.swing.JComboBox<String> cmbpilihansewafrmrental;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser tanggalrental;
    private javax.swing.JTable tblrental;
    private javax.swing.JTextField txtbmmobilfrmrental;
    private javax.swing.JTextField txthargarentalfrmrental;
    private javax.swing.JTextField txtidrentalfrmrental;
    private javax.swing.JTextField txtnamamobilfrmrental;
    private javax.swing.JTextField txtnamapenyewafrmrental;
    private javax.swing.JTextField txtstatusfrmrental;
    // End of variables declaration//GEN-END:variables

    private void Clear() {
        txtidrentalfrmrental.setText("");
        cmbpilihansewafrmrental.setSelectedItem("PILIH");
        cmbidpenyewafrmrental.setSelectedItem("");
        cmbidmobilfrmrental.setSelectedItem("");
        txtnamapenyewafrmrental.setText("");
        txtnamamobilfrmrental.setText("");
        tanggalrental.setDate(null);
        txtbmmobilfrmrental.setText("");
        txthargarentalfrmrental.setText("");
        txtstatusfrmrental.setText(status);
        
    }

    private void KoneksiRental() {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            connectionrental=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_rentalmobilsecond","root","");
            System.out.println("Koneksi Berhasil");
        } catch (Exception e) {
            System.out.println("Koneksi Gagal");
          
      }
    }

    private void TampilData(String sqlrental1) {
         DefaultTableModel datalist = new DefaultTableModel ();
        datalist.addColumn("No");
        datalist.addColumn("ID Rental");
        datalist.addColumn("ID Penyewa");
        datalist.addColumn("ID Mobil");
        datalist.addColumn("Harga Rental");
        datalist.addColumn("Tanggal Rental");
        datalist.addColumn("Status");
        try{
            int i =1;
            statemenrental=connectionrental.createStatement();
            resultsetrental=statemenrental.executeQuery("select * from tabel_rental");
            while (resultsetrental.next())
                datalist.addRow(new Object[]{
                    (""+i++),
                    resultsetrental.getString(1),     resultsetrental.getString(2),
                    resultsetrental.getString(3),     resultsetrental.getString(6),
                    resultsetrental.getString(7),     resultsetrental.getString(8),
                });
            tblrental.setModel(datalist);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Tampil!!\n"+e.getMessage());
    }
}
}
