/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmobil2019;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class frmpengembalian extends javax.swing.JFrame {

  private Connection connection;
  private Statement statement;
  private ResultSet resultset;
  private String db_sql="";
  
  private String idpengembalian,pilihankembali,idrental,idpenyewa,idmobil,namapenyewa,namamobil,tanggalrental,tanggalkembali,status,aliaskd;
  private int hargarental,lama,totalbayar;
    public frmpengembalian() {
        initComponents();
        Koneksi();
        Clear();
        TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidpengembalian = new javax.swing.JTextField();
        cmbpilihankembali = new javax.swing.JComboBox<>();
        cmbidrental = new javax.swing.JComboBox<>();
        txtidpenyewa = new javax.swing.JTextField();
        txtidmobil = new javax.swing.JTextField();
        txtnamapenyewa = new javax.swing.JTextField();
        txtnamamobil = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txthargarental = new javax.swing.JTextField();
        txtlama = new javax.swing.JTextField();
        txttotalbayar = new javax.swing.JTextField();
        txtstatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkembali = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jdctanggalrental = new com.toedter.calendar.JDateChooser();
        jdctanggalkembali = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/car.png"))); // NOI18N

        jLabel2.setText("ID Pengembalian");

        jLabel3.setText("Pilihan Kembali");

        jLabel4.setText("ID Rental");

        jLabel5.setText("ID Penyewa");

        jLabel6.setText("ID Mobil");

        jLabel7.setText("Nama Penyewa");

        jLabel8.setText("Nama Mobil");

        txtidpengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpengembalianActionPerformed(evt);
            }
        });
        txtidpengembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidpengembalianKeyPressed(evt);
            }
        });

        cmbpilihankembali.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "KEMBALI" }));
        cmbpilihankembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpilihankembaliActionPerformed(evt);
            }
        });

        cmbidrental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        cmbidrental.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbidrentalItemStateChanged(evt);
            }
        });
        cmbidrental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbidrentalActionPerformed(evt);
            }
        });

        jLabel9.setText("Harga Rental");

        jLabel10.setText("Tanggal Rental");

        jLabel11.setText("Tanggal Kembali");

        jLabel12.setText("Lama");

        jLabel13.setText("Total Bayar");

        jLabel14.setText("Status");

        txtlama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlamaActionPerformed(evt);
            }
        });

        tblkembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(tblkembali);

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jdctanggalrental.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdctanggalrentalPropertyChange(evt);
            }
        });

        jdctanggalkembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdctanggalkembaliPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtnamapenyewa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtidmobil, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtidpenyewa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbidrental, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbpilihankembali, javax.swing.GroupLayout.Alignment.LEADING, 0, 189, Short.MAX_VALUE)
                                    .addComponent(txtidpengembalian, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnamamobil))
                                .addGap(201, 201, 201)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txthargarental, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(txtlama, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(txttotalbayar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(txtstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(jdctanggalkembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jdctanggalrental, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(83, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtidpengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(jdctanggalrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(cmbpilihankembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(jdctanggalkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthargarental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(cmbidrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtidpenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtidmobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtnamapenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtnamamobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnsimpan)
                                    .addComponent(btnbatal)
                                    .addComponent(btnedit)
                                    .addComponent(btnhapus)
                                    .addComponent(btnkeluar)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 313, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jMenu1.setText("Master");

        jMenuItem1.setText("Formmobil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Formpenyewa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        jMenuItem3.setText("FormRental");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("FormPengembalian");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Keluar");

        jMenuItem5.setText("Keluar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        formmobil mobil = new formmobil();
        mobil.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        formpenyewa penyewa= new formpenyewa();
        penyewa.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        formrental rental = new formrental();
        rental.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        frmpengembalian kembali = new frmpengembalian();
        kembali.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        frmlogin login=new frmlogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void cmbidrentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbidrentalActionPerformed
       
        
    }//GEN-LAST:event_cmbidrentalActionPerformed

    private void cmbpilihankembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpilihankembaliActionPerformed
        // TODO add your handling code here:
        if (cmbpilihankembali.getSelectedItem()=="KEMBALI"){
            cmbidrental.removeAllItems();
            cmbidrental.addItem("PILIH");
            try{
                status=String.valueOf(cmbpilihankembali.getSelectedItem());
                status= "SEWA";
                db_sql = "select * from tabel_rental where status = '" + status + "'";
                statement = connection.createStatement();
                resultset=statement.executeQuery(db_sql);
                while(resultset.next()){
                    aliaskd = resultset.getString("idrental");
                    cmbidrental.addItem(aliaskd);
                }
            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Menampilkan ID Rental\n"+ e.getMessage());
            }
        }
    }//GEN-LAST:event_cmbpilihankembaliActionPerformed

    private void cmbidrentalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbidrentalItemStateChanged
        
        try{
            db_sql="select * from tabel_rental where idrental='"+cmbidrental.getSelectedItem()+"'";
            statement=connection.createStatement();
            resultset=statement.executeQuery(db_sql);
            while(resultset.next()){
                txtidpenyewa.setText(resultset.getString("idpenyewa"));
                txtidmobil.setText(resultset.getString("idmobil"));
                txtnamapenyewa.setText(resultset.getString("namapenyewa"));
                txtnamamobil.setText(resultset.getString("namamobil"));
                jdctanggalrental.setDate(resultset.getDate("tanggalrental"));
                txthargarental.setText(resultset.getString("hargarental"));
                txtstatus.setText(resultset.getString("status"));
                
                jdctanggalrental.setEnabled(false);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan\n"+e.getMessage());
        }
    }//GEN-LAST:event_cmbidrentalItemStateChanged

    private void jdc_tanggalkembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdc_tanggalkembaliPropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jdc_tanggalkembaliPropertyChange

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        idpengembalian=String.valueOf(txtidpengembalian.getText());
        idrental=cmbidrental.getItemAt(cmbidrental.getSelectedIndex());
        idpenyewa=String.valueOf(txtidpenyewa.getText());
        idmobil=String.valueOf(txtidmobil.getText());
        namapenyewa=String.valueOf(txtnamapenyewa.getText());
        namamobil=String.valueOf(txtnamamobil.getText());
        hargarental=Integer.parseInt(txthargarental.getText());
        lama=Integer.parseInt(txtlama.getText());
        totalbayar=Integer.parseInt(txttotalbayar.getText());
        status=String.valueOf(txtstatus.getText());
        
       
        
        try{
            db_sql="insert into tabelpengembalian(idpengembalian,idpenyewa,idmobil,tanggalrental,tanggalkembali,lama,totalbayar,status,idrental,namapenyewa,namamobil,hargarental)value"
                    + "('"+idpengembalian+"','"+idpenyewa+"','"+idmobil+"','"+tanggalrental+"','"+tanggalkembali+"','"+lama+"','"+totalbayar+"','"+status+"','"+idrental+"','"+namapenyewa+"','"+namamobil+"','"+hargarental+"')";
            statement=connection.createStatement();
            statement.execute(db_sql);
            Clear();
            TampilData();
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Menyimpan Data\n"+e.getMessage());
        }
        
        try{
            status="READY";
            db_sql="update tabel_mobil set status='"+status+"' where idmobil='"+idmobil+"'";
            statement=connection.createStatement();
            statement.execute(db_sql);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Maaf Erorr\n"+e.getMessage());
        }
        
         try{
            status="SELESAI";
            db_sql="update tabel_rental set status='"+status+"' where idrental='"+idrental+"'";
            statement=connection.createStatement();
            statement.execute(db_sql);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Maaf Erorr\n"+e.getMessage());
        }
         try{
             status="SELESAI";
             db_sql="update tabelpengembalian set status='"+status+"' where idpengembalian='"+idpengembalian+"'";
             statement=connection.createStatement();
             statement.execute(db_sql);
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Maaf Erorr\n"+e.getMessage());
         }
         
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void jdc_tanggalrentalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdc_tanggalrentalPropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jdc_tanggalrentalPropertyChange

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        hargarental=Integer.parseInt(txthargarental.getText());
        idpengembalian=String.valueOf(txtidpengembalian.getText());
        try{
            db_sql="update tabelpengembalian set idpengembalian='"+idpengembalian+"', hargarental='"+hargarental+"', tanggalkembali='"+tanggalkembali+"'";
            statement=connection.createStatement();
            statement.execute(db_sql);
            JOptionPane.showMessageDialog(null, "Berhasil Mengubah Data");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Mengubah Data\n"+e.getMessage());
        }
        
    }//GEN-LAST:event_btneditActionPerformed

    private void txtidpengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpengembalianActionPerformed

    private void txtidpengembalianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpengembalianKeyPressed
        // TODO add your handling code here:
        idpengembalian=String.valueOf(txtidpengembalian.getText());
        int tekanenter=evt.getKeyCode();
        if(tekanenter==10){
            try{
            db_sql="select * from tabelpengembalian where idpengembalian='"+idpengembalian+"'";
        
            statement=connection.createStatement();
            resultset=statement.executeQuery(db_sql);
            while(resultset.next()){
                cmbidrental.setSelectedItem(resultset.getString("idrental"));
                txtidpenyewa.setText(resultset.getString("idpenyewa"));
                txtidmobil.setText(resultset.getString("idmobil"));
                jdctanggalrental.setDate(resultset.getDate("tanggalrental"));
                jdctanggalkembali.setDate(resultset.getDate("tanggalkembali"));
                txtlama.setText(resultset.getString("lama"));
                txttotalbayar.setText(resultset.getString("totalbayar"));
                txtstatus.setText(resultset.getString("status"));
                txtnamapenyewa.setText(resultset.getString("namapenyewa"));
                txtnamamobil.setText(resultset.getString("namamobil"));
                txthargarental.setText(resultset.getString("hargarental"));
                
                JOptionPane.showMessageDialog(null, "Data Ditemukan");
                jdctanggalrental.setEnabled(false);
                cmbpilihankembali.setEnabled(false);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Ditemukan\n"+e.getMessage());
        }
            
            try{
                cmbidrental.removeAllItems();
                db_sql="select * from tabelpengembalian where idpengembalian='"+idpengembalian+"'";
                statement=connection.createStatement();
                resultset=statement.executeQuery(db_sql);
                while(resultset.next()){
                    String Aliasid=resultset.getString("idmobil");
                    cmbidrental.addItem(Aliasid);
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Gagal Menampilkan Id Rental\n"+e.getMessage());
                
            }
        }
    }//GEN-LAST:event_txtidpengembalianKeyPressed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        idpengembalian=String.valueOf(txtidpengembalian.getText());
        
        try{
            db_sql="delete from tabelpengembalian where idpengembalian='"+idpengembalian+"'";
            statement=connection.createStatement();
            statement.execute(db_sql);
            TampilData();
            Clear();
            JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Menghapus Data\n"+e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void txtlamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlamaActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_txtlamaActionPerformed

    private void jdctanggalkembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdctanggalkembaliPropertyChange
        // TODO add your handling code here:
       if(jdctanggalkembali.getDate()!=null){
         SimpleDateFormat kembali=new SimpleDateFormat("yyyy-MM-dd");
        tanggalkembali=kembali.format(jdctanggalkembali.getDate());
       }
        
        try{
            DateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
            Date rental=jdctanggalrental.getDate();
            Date mkembali=jdctanggalkembali.getDate();
            long mdipinjam=rental.getTime();
            long mdikembalikan=mkembali.getTime();
            long dif=mdikembalikan-mdipinjam;
            long lamapinjam=dif/(24*60*60*1000);
            txtlama.setText(Long.toString(lamapinjam));
            hargarental=Integer.parseInt(txthargarental.getText());
            lama=Integer.parseInt(txtlama.getText());
            totalbayar=hargarental*lama;
            txttotalbayar.setText(String.valueOf(totalbayar));
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null,"Tanggal Error "+e.getMessage());
        }
        
    
    }//GEN-LAST:event_jdctanggalkembaliPropertyChange

    private void jdctanggalrentalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdctanggalrentalPropertyChange
        // TODO add your handling code here:
        if(jdctanggalrental.getDate()!=null){
            SimpleDateFormat simple=new SimpleDateFormat("yyyy-MM-dd");
            tanggalrental=simple.format(jdctanggalrental.getDate());
        }
    }//GEN-LAST:event_jdctanggalrentalPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmpengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmpengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmpengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmpengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmpengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cmbidrental;
    private javax.swing.JComboBox<String> cmbpilihankembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdctanggalkembali;
    private com.toedter.calendar.JDateChooser jdctanggalrental;
    private javax.swing.JTable tblkembali;
    private javax.swing.JTextField txthargarental;
    private javax.swing.JTextField txtidmobil;
    private javax.swing.JTextField txtidpengembalian;
    private javax.swing.JTextField txtidpenyewa;
    private javax.swing.JTextField txtlama;
    private javax.swing.JTextField txtnamamobil;
    private javax.swing.JTextField txtnamapenyewa;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txttotalbayar;
    // End of variables declaration//GEN-END:variables

    private void Koneksi() {
         try{
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_rentalmobilsecond","root","");
            System.out.println("Koneksi Berhasil");
        } catch (Exception e) {
            System.out.println("Koneksi Gagal");
          
      }
    }

    private void Clear() {
        txtidpengembalian.setText("");
        cmbpilihankembali.setSelectedItem("PILIH");
        cmbidrental.setSelectedItem("PILIH");
        txtidpenyewa.setText("");
        txtidmobil.setText("");
        txtnamapenyewa.setText("");
        txtnamamobil.setText("");
        txthargarental.setText("");
        txtlama.setText("");
        txttotalbayar.setText("");
        txtstatus.setText("");
    }

    private void TampilData() {
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("No");
        datalist.addColumn("ID Pengembalian");
        datalist.addColumn("ID Mobil");
        datalist.addColumn("ID Penyewa");
        datalist.addColumn("Tanggal Kembali");
        datalist.addColumn("Lama");
        datalist.addColumn("Total Bayar");
        
                try{
            int i = 1;
            statement=connection.createStatement();
            resultset=statement.executeQuery("SELECT * FROM tabelpengembalian");
            while(resultset.next())
                datalist.addRow(new Object[]{
                    (""+i++),
                    resultset.getString(1), resultset.getString(3),
                    resultset.getString(2), resultset.getString("tanggalkembali"),
                    resultset.getString("lama"), resultset.getString("totalbayar"),
                    
                    
                   
                });
            tblkembali.setModel(datalist);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Tampil"+e.getMessage());
    }
}}
